/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package child;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest2 {


    @Test
    public void test1()
    {
        assertEquals(1,1);
    }
}
